name: Swift tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  SWIFT_ETHEREUM_RPC_URL: ${{ secrets.SWIFT_ETHEREUM_RPC_URL }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
